### ISSUE TITLE
Bugs using QAX 2.10

### ISSUE THREAD

**Issue by monocilindro** [ausseabed/hyo2_qax#3]
I am getting the following error message when processing Kmall files from a Kongsberg EM2040 sounder
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "hyo2\qax\lib\check_executor.py", line 188, in run
  File "hyo2\qax\lib\check_executor.py", line 80, in run
  File "hyo2\mate\qax\plugin.py", line 141, in run
  File "hyo2\mate\lib\check_runner.py", line 161, in run_checks
  File "hyo2\mate\lib\scan_KMALL.py", line 45, in scan_datagram
  File "KMALL\kmall.py", line 102, in read_datagram
  File "KMALL\kmall.py", line 202, in read_EMdgmIIP
  File "KMALL\kmall.py", line 3863, in translate_installation_parameters_todict
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by boyd03m** [comment]
hi,

are you able to supply a small kmall file that causes the error and we will look into the issue.  let me know if you need an avenue to supply the file?

**Comment by monocilindro** [comment]
Hi,

Sure, please provide me your email address so that I can send you a DropBox
link to the file (it is about 60 MB in size)

Best

Jose Cordero
Cadiz,Spain

**Comment by boyd03m** [comment]
are you able to upload to here?
https://cloudstor.aarnet.edu.au/plus/s/us3OAWiKIl0w9BX

**Comment by monocilindro** [comment]
It is already done

**Comment by boyd03m** [comment]
I beleive I have solved this bug however I have limited test data to confirm.  you wouldn't by chance have any small kmall files less than 50mb that you might be willing to assist us with?  I probably need 5 or so?

**Comment by monocilindro** [comment]
Sure, no problem. I am uploading a bunch of file to your folder at cloudstor
