### ISSUE TITLE
GGOutliers fails to run

### ISSUE THREAD

**Issue by sixy6e** [ausseabed/hyo2_qax#34]
The GGOutliers check fails to run with an error message of:

```python
Traceback (most recent call last):
  File "ausseabed\ggoutlier\lib\ggoutlier_check.py", line 300, in run
  File "ausseabed\ggoutlier\lib\ggoutlier_check.py", line 298, in run
  File "ggoutlier.py", line 178, in main
  File "ggoutlier.py", line 420, in process2
  File "pylasfile.py", line 120, in writepointlist
  File "pylasfile.py", line 414, in writepoints
struct.error: argument out of range
```

In short, the LAS writer is attempting to write a number outside the int32 range, and the binary struct subsequently fails.

**Comment by sixy6e** [comment]
From the output CSV, the offending point is:

```bash
687445.8750,7467638.0000,-340282346638528859811704183484516925440.0000,0.4407,0.1925,-16.0840
```

Where the third value (representing Z) is the nodata value used for the array.

**Comment by pktrigg** [comment]
Hi Josh,
this is a really big depth value!

some thoughts...

1. Do you know if this is the NODATA value?
2. is it just a random depth?
3. is this a RGB file rather than a floating point file and we are simply interpreting the tif incorrectly?
4. as we use int32 I am not sure waht to do with a value of this magnitude.  it is so far outside any form of useful reality its confusing what to do with such a problem

regards

**Comment by pktrigg** [comment]
is it possible to share the tif file so we can try to find a solution?

**Comment by sixy6e** [comment]
Hi @pktrigg 

Yep, that value does correspond with the nodata value used by the array.

The file contains (depth, density, uncertainty) and I'll email you the GeoTIFF and the CSV output by ggoutlier.

I haven't read through the guts of ggoutlier to see if nodata values can be handled specifically. But I know the process does apply a median filter.  Potentially, any nodata values could be replaced with NaN, as I'm pretty sure the median filter from skimage caters for NaN by inserting NaN at the locations where NaN existed in the original array.

In addition, once pixels have been identified as an outlier, is to filter the list to ignore any points with a Z value that corresponds with the input nodata value. This would ensure they're never written out nor reported back to QAX.

Just so you know, the error wasn't triggered under _order 1a_ nor _order 1b_, but it was triggered under _exclusiveorder_. I haven't checked the others, but the fact that it does occur at least once is not ideal.

Relating to the laswriter section where it failed, it might also be worth catching any errors that occur during the struct binary conversion so that the opened file can be safely closed in the event of a failed binary conversion. QAX attempts to cleanup the working directory created for ggoutlier to write to, but fails as the las file is still opened by another process even though ggoutlier crashed.

**Comment by sixy6e** [comment]
Just realised I hadn't finished updating the second comment describing the nodata value :sweat_smile:

**Comment by pktrigg** [comment]
if you can send me the input tif file, I will debug and sort this out.  I thought we mask out the NODATA already, so maybe its not set in the header.
for sure I can put some try catch in the writer as well!

**Comment by sixy6e** [comment]
I've just sent the email which also describes another potential issue related to pixel location lookup. It may also be a start point that leads to the error eg the reported coords are not centre, but on the edge, so when doing a nearest lookup, it could be retrieving the Z value from the wrong pixel, if the coord is offset slightly.

**Comment by sixy6e** [comment]
The nodata value is definitely in the header:

```python
>>> import rasterio
>>> ds = rasterio.open("teste_qax.tif")
>>> ds.nodata
-3.4028234663852886e+38
>>>
```

**Comment by pktrigg** [comment]
ahh, good! thats exactly what I would do!
I will make it work when I get the tif file:-)

**Comment by pktrigg** [comment]
evening, I ran the ggoutlier code on github against the supplied tif file and it ran like a charm.  no errors.  The las file, txt file and shp file of outliers was created as we would hope.  this means there is a different issue in play here.
![image](https://github.com/user-attachments/assets/cb6a78e2-5f15-484d-a751-03531e508fdd)

The code does check for NODATA when we compute the outliers...

![image](https://github.com/user-attachments/assets/892afc3d-47c8-4032-8949-ddf12aaba35f)


Number of CPUs 12
QC to Survey Standard: order1a
Survey_Standard: Name:order1a,a=0.5,b=0.013,TVU(d)=sqrt((a*a)+(b*d)^2)
Processing file: C:/sampledata/ggoutlier/problemfile/teste_qax.tif
Bands in tif file: ('depth', 'density', 'uncertainty')
Processing band file: C:/sampledata/ggoutlier/problemfile\teste_qax_GGOutlier_20240918-185203\teste_qax_Depth.tiff
Source file size is 256 wide * 1792 high == 458752 pixels.  This is potentially too large for your system memory so we will tile it..
Tiling into 1 tiles...
Tiling to conserve memory...: [####################] 100.0% DONE
Computing TVU surface: C:/sampledata/ggoutlier/problemfile/teste_qax_GGOutlier_20240918-185203\teste_qax_Depth.tiff_TILE_0_0_TVU_Allowable.tif 
Computing DeltaZ surface: C:/sampledata/ggoutlier/problemfile/teste_qax_GGOutlier_20240918-185203\teste_qax_Depth.tiff_TILE_0_0_DeltaZ.tif 
Pass1: Finding Outliers...
Backend TkAgg is interactive backend. Turning interactive mode on.
Pass2: double checking outliers at edges of survey...
Analysing Tiles for Outliers...: [--------------------] 0.0%Points checked: 458,752
Points outside specification: 149
Percentage outside specification: 0.0324794
Writing outliers to: C:/sampledata/ggoutlier/problemfile\teste_qax_GGOutlier_20240918-185203\teste_qax_OutlierPoints.shp
Significant Features for Review: 50
Created TXT file of outliers: C:/sampledata/ggoutlier/problemfile\teste_qax_GGOutlier_20240918-185203\teste_qax_OutlierPoints.txt
Created LAS file of outliers: C:/sampledata/ggoutlier/problemfile\teste_qax_GGOutlier_20240918-185203\teste_qax_OutlierPoints.las
Creating a regional file for QC purposes
Creating a regional file for QC purposes: C:/sampledata/ggoutlier/problemfile\teste_qax_GGOutlier_20240918-185203\teste_qax_RegionalDepth.tiff
QC complete at: 2024-09-18 18:53:21.617166
Bands in tif file: ('depth', 'density', 'uncertainty')
Creating a Allowable TVU file for QC purposes: C:/sampledata/ggoutlier/problemfile\teste_qax_GGOutlier_20240918-185203\teste_qax_Depth_TVU_Allowable.tiff 
Created TVU TIF file for validation in GIS: C:/sampledata/ggoutlier/problemfile\teste_qax_GGOutlier_20240918-185203\teste_qax_Depth_TVU_Allowable.tiff 
QC Duration:77.802s
Creating Report...
Report Complete
QC complete at: 2024-09-18 18:53:26.422981

**Comment by pktrigg** [comment]
I am wondering if QAX is not presenting the same tif file to ggoutliers as the user is specifying?

**Comment by sixy6e** [comment]
I'll check in the morning the exact settings used. It didn't error on some of the settings like  1a and 1b. It might've been exclusive that I could get it to fail. The error was submitted by another user and I couldn't get it to repeat the error until I change the config. I'm not sure what config setting they were using but will follow up on that as well

I'll build another vm to ensure there are no other files for qax to use. Looking at the qax code it just passes the pathname through but I'll do some additional logging as well to confirm it.

**Comment by pktrigg** [comment]
I have added a test to cut out row from numpy outlier list if the values in the Z column are within not an int32 valid range

 cut out row if the values in the 3rd column are within an int32 valid range
xyz = xyz[(xyz[:,2] > -2147483648) & (xyz[:,2] < 2147483647)]

This should clip out these crazy outliers, but I am unable to test within the qax environment directly.  can you please merge the code and see if ok.  it should be fine!

**Comment by pktrigg** [comment]
I pushed it to github

**Comment by sixy6e** [comment]
Awesome nice work. Will test it out tomorrow and get a build for the user who submitted the error a version to test as well

**Comment by pktrigg** [comment]
ahh,  i just tested it with -standard specialorder and replicated the bug.  there was 1 sounding with a bad z value.
I then re-instated the bug fix and it ran like a charm, so I think the recent checkin will resolve the issue.

**Comment by sixy6e** [comment]
Ah fantastic. Even better knowing that the filtering fix works.

I'll also upload a screenshot of the points overlayed on the image and you'll see what I'm referring to regarding their positions on the grid.

**Comment by sixy6e** [comment]
I've dug into the coordinate calculations, and they appear more likely to be the root cause of the issue.

The initial thought was that this [line](https://github.com/pktrigg/ggoutlier/blob/main/ggmbesstandard.py#L175) was problematic, but I was only skimming and missed the fact that the inputs are arrays [0, ..., width-1] not a singular value for each of the dimensions (height and width).  This process is correct and returns the pixel centres in real-world coordinates.

The issue arises when they're cast to float32 in the immediately following [two lines](https://github.com/pktrigg/ggoutlier/blob/main/ggmbesstandard.py#L176-L177).
This results in a loss of precision causing the points to now be offset from their pixel centres, as seen below:

![pixel-offsets-f32-f64](https://github.com/user-attachments/assets/2bc9ef8e-b124-448a-8a1c-b83c441b34b8)


The red triangles are the outliers flagged by ggoutlier, and the green circles are the pixel centres calculated **prior** to casting to float32.

Small snippet from python:
```python
>>> xsf64[0]
np.float64(687435.625)
>>> xsf32[0]
np.float32(687435.6)
>>> ysf64[0]
np.float64(7467788.375)
>>> ysf32[0]
np.float32(7467788.5)
```

This becomes an issue down the line when rasterio is used to [retrieve the value from the pixel closest](https://github.com/pktrigg/ggoutlier/blob/main/ggoutlier.py#L338) to the input real world coordinate.

For this particular data file, the truncated coordinates have put the values right on the edges between pixels.  A bit like balancing a value on a razor's edge (machine Epsilom, precision error etc), and as they're float32 values, there's not a lot of precision to work with, coupled with the fact these are projected coordinates taking up most of the exponent.

This would definitely be a reason why a nodata value has been retrieved even though the rest of your code is catering for nodata values. And also accounts for why it doesn't happen all the time. It was a case where the pixel resolution resulted in point locations that fell precisely on pixel edges after float32 casting.

Here is a picture of the outliers with coordinates that retained the full precision.

![pixel-offsets-f32-f64-fix](https://github.com/user-attachments/assets/e194a068-5218-4946-bf52-1dd9d3a3c7a1)

The green rhombuses represent the new locations, the red triangles are the outliers from the original calculations. As you can see, southern-most red triangle had the pixel containing nodata as an outlier, and now the green rhombus represents the correct location. This fix was applied to commit 022caba (the commit prior last nights' updates), and successfully finished with the *specialorder* standard.

I can do a PR for it if you like, to apply on top of your updates from last night.  It'd only be 3 lines; changed/removed the float32 casting.

I'll email you the vectors of the point locations for the entire grid. One using float64 and the other float32.

**Comment by sixy6e** [comment]
I did find another issue regarding the filtering out of inliers:

https://github.com/pktrigg/ggoutlier/blob/main/ggmbesstandard.py#L216

This would remove any points that have negative coordinates, eg:

```python
>>> import numpy
>>> x = [1, -1, 1, 1, -1]
>>> y = [2, 2, -2, 2, -2]
>>> z = [3, 3, 3, -3, -3]
>>> xyz = numpy.stack((x, y, z), axis=1)
>>> xyz
array([[ 1,  2,  3],
       [-1,  2,  3],
       [ 1, -2,  3],
       [ 1,  2, -3],
       [-1, -2, -3]])
>>> xyz.shape
(5, 3)
>>> xyz[numpy.all(xyz > 0, axis=1)]
array([[1, 2, 3]])
```

`numpy.all` would be checking that all values across axis 1, i.e. that for a single row (point) each of the x,y,z values must be true (result from xyz > 0).

To demonstrate, here's the summation across axis 1:

```python
>>> numpy.sum(xyz, axis=1)
array([ 6,  4,  2,  0, -6])
```

Doing a boolean check for `> 0` would result in undesired behaviour for lon/lat coords, and projected coords containing negative values.
