### ISSUE TITLE
Algorithm independent density check fails to run

### ISSUE THREAD

**Issue by lachlanhurst** [ausseabed/hyo2_qax#36]
Using QAX v3.2.4 installed from the setup exe.

Steps to reproduce.
- Select 'test' profile
- check 'Algorithm independent density check'
- Specify input files (example is attached)
- Run checks
- Output for check shows error message shown below.

At a guess I'd say one of the dependency updates has broken the point cloud checks. Have attached a zip file containing the programmatically generated test data, but I'm sure this would occur with any set of inputs.

[test_data.zip](https://github.com/user-attachments/files/17198080/test_data.zip)

Error Messages:
Traceback (most recent call last):
  File "ausseabed\mbespc\qax\plugin.py", line 146, in _run_algorithm_indepenent_density_check
  File "ausseabed\mbespc\lib\density_check.py", line 90, in run
  File "geopandas\geodataframe.py", line 1536, in to_file
  File "geopandas\io\file.py", line 651, in _to_file
  File "geopandas\io\file.py", line 139, in _check_engine
ImportError: The 'to_file' method requires the 'pyogrio' or 'fiona' package, but neither is installed or imports correctly.
Importing pyogrio resulted in: GDAL DLL could not be found.  It must be on the system PATH.
Importing fiona resulted in: No module named 'fiona'

**Comment by sixy6e** [comment]
Thanks for detailed description @lachlanhurst.  I can confirm on my end that it fails with the same error.

I'll start digging into it this afternoon or early next week.

**Comment by sixy6e** [comment]
So adding `fiona` to the build is one way to resolve the issue. Looks like `geopandas > 1.0` now defaults to `pyogrio` instead of `fiona`.

What is weird is that `fiona` also requires a GDAL DLL. The `fiona` module adds it's own libs directory named `fiona.libs` which contains a bunch of DLL's including GDAL.  Removing that additional `fiona.libs` directory and the error returns.
The current build (3.2.4) already includes the `pyogrio` module, which also adds its own `pyogrio.libs` directory which also contains a GDAL DLL.  Why `pyogrio` can't find it's own dependent DLL's is a puzzle.  QAX doesn't do anything specific for DLL's to be found when `fiona` is used, so the same should be true for `pyogrio`.

I'll leave it alone and assume it is a conda/pyogrio issue simply because `fiona` is bundled the same way and no additional effort from the QAX side of things is required for those DLL's to be discovered.

This page reports a very similar if not identical issue.

https://stackoverflow.com/questions/72916212/pyinstaller-and-pyogrio-write-dataframe-problem-in-graphical-exe
